apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chutes-network-policy
  labels:
    {{- include "chutes.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "chutes.labels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              - 169.254.0.0/16
              - 100.64.0.0/10
      ports:
        - protocol: TCP
          port: 443
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: chutes-squid
      ports:
        - protocol: TCP
          port: 3128
