---
- name: Restart k3s
  ansible.builtin.service:
    name: k3s
    state: restarted
  listen: restart k3s

- name: Restart k3s agent
  ansible.builtin.service:
    name: k3s-agent
    state: restarted
  listen: restart k3s agent

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Restart timesyncd service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted

- name: Restart system
  listen: system reboot
  ansible.builtin.reboot:
    reboot_timeout: 600
    pre_reboot_delay: 10
    post_reboot_delay: 30
    test_command: uptime
