{{- define "redis.url" -}}
redis://:$(REDIS_PASSWORD)@redis:6379
{{- end }}

{{- define "postgresql.url" -}}
postgresql+asyncpg://{{ .Values.postgres.database.user }}:$(POSTGRES_PASSWORD)@postgres:5432/{{ .Values.postgres.database.name }}
{{- end }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: audit-exporter
spec:
  schedule: "1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 5
      template:
        metadata:
          labels:
            postgres-access: "true"
            redis-access: "true"
        spec:
          {{- with .Values.auditExporter.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: audit-export
            image: {{ .Values.auditExporter.image }}
            imagePullPolicy: Always
            command: ["poetry", "run", "python", "audit_exporter.py"]
            env:
              - name: MINER_SS58
                valueFrom:
                  secretKeyRef:
                    name: miner-credentials
                    key: ss58
              - name: MINER_SEED
                valueFrom:
                  secretKeyRef:
                    name: miner-credentials
                    key: seed
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: redis-secret
                    key: {{ .Values.redis.password.passwordKey }}
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: {{ .Values.postgres.database.passwordKey }}
              - name: POSTGRESQL
                value: {{ include "postgresql.url" . }}
              - name: REDIS_URL
                value: {{ include "redis.url" . }}
              - name: VALIDATORS
                value: {{ .Values.validators | toJson | quote }}
          restartPolicy: OnFailure
