apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chutes-network-policy
  labels:
    {{- include "chutes.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "chutes.labels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: chutes-squid
      ports:
        - protocol: TCP
          port: 3128
