apiVersion: batch/v1
kind: CronJob
metadata:
  name: failed-chute-cleanup
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: chutes
          {{- with .Values.failedChuteCleanup.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: cleanup
            image: {{ .Values.failedChuteCleanup.image }}
            imagePullPolicy: Always
            command: ["kubectl", "delete", "pods", "--field-selector=status.phase=Failed", "-l", "chutes/chute=true", "-n", "chutes"]
          restartPolicy: OnFailure
