{{- $redisSecret := lookup "v1" "Secret" .Release.Namespace "redis-secret" -}}
{{- if not $redisSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.password.passwordKey }}: {{ default (randAlphaNum 32) .Values.redis.password.value | b64enc }}
{{- end }}
---
{{- $postgresSecret := lookup "v1" "Secret" .Release.Namespace "postgres-secret" -}}
{{- if not $postgresSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.postgres.database.passwordKey }}: {{ randAlphaNum 32 | b64enc }}
{{- end }}