{{- $root := . -}}
{{- range .Values.validators.supported }}
apiVersion: v1
kind: Service
metadata:
  name: registry-{{ .hotkey | lower }}
  labels:
    {{- include "registry.labels" $root | nindent 4 }}
spec:
  type: NodePort
  internalTrafficPolicy: Local
  externalTrafficPolicy: Local
  ports:
    - port: {{ $root.Values.registry.service.port }}
      targetPort: {{ $root.Values.registry.service.targetPort }}
      protocol: TCP
      nodePort: {{ $root.Values.registry.service.nodePort }}
      name: http
  selector:
    {{- include "registry.labels" $root | nindent 4 }}
---
{{- end }}
