apiVersion: v2
name: chutes-miner-gpu
description: Helm chart for chutes.ai GPU nodes
version: 0.1.3-dev
appVersion: "0.1.0"
type: application
maintainers:
  - name: Jon Durbin
    email: jon@chutes.ai
  - name: namoray
    email: namoray@rayonlabs.ai
  - name: Kyle Widmann
    email: kyle@chutes.ai
kubeVersion: ">=1.19.0-0"
