---
- name: Setup GPU operator
  ansible.builtin.include_tasks: setup_gpu_operator.yml
  tags: gpu-operator

- name: Setup monitoring
  ansible.builtin.include_tasks: setup_monitoring.yml
  tags: monitoring