---
- name: Check if miner credentials secret already exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: miner-credentials
    namespace: chutes
    context: "{{ inventory_hostname }}"
  register: existing_miner_credentials

- name: Debug
  ansible.builtin.debug:
    msg: "{{ existing_miner_credentials }}"

- name: Generate miner credentials
  when: existing_miner_credentials.resources | length == 0
  block:
    - name: Create miner-credentials secret
      kubernetes.core.k8s:
        state: present
        context: "{{ inventory_hostname }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: miner-credentials
            namespace: chutes
          type: Opaque
          data:
            ss58: "{{ ss58_address | b64encode }}"
            seed: "{{ secret_seed | b64encode }}"
        kubeconfig: "{{ kubeconfig_path | default(omit) }}"
