- name: Add Chutes Helm repository
  kubernetes.core.helm_repository:
    name: chutes
    repo_url: https://rayonlabs.github.io/chutes-miner

- name: Update Helm repositories
  shell: helm repo update

- name: Copy custom values
  ansible.builtin.copy:
    src: "{{ chart_values }}"
    dest: /tmp/chutes-miner.yaml
    mode: preserve
  register: copy_values_result
  changed_when: copy_values_result.changed

- name: Install or upgrade Miner charts
  ansible.builtin.command: >
    helm upgrade --install chutes chutes/chutes-miner
    --namespace chutes
    --kube-context {{ inventory_hostname }}
    --create-namespace
    -f /tmp/chutes-miner.yaml
  register: miner_deployment
  changed_when: miner_deployment.rc == 0

- name: Display Miner deployment result
  debug:
    var: miner_deployment