- name: Read hotkey file
  ansible.builtin.slurp:
    src: "{{ hotkey_path }}"
  register: hotkey_content
  no_log: true

- name: Extract credentials
  ansible.builtin.set_fact:
    miner_credentials:
      ss58_address: "{{ (hotkey_content.content | b64decode | from_json).ss58Address }}"
      secret_seed: "{{ (hotkey_content.content | b64decode | from_json).secretSeed | regex_replace('^0x', '') }}"
  no_log: true

- name: Distribute credentials to all cluster nodes
  ansible.builtin.set_fact:
    miner_ss58_address: "{{ miner_credentials.ss58_address }}"
    miner_secret_seed: "{{ miner_credentials.secret_seed }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['control'] + groups['workers'] }}"
  no_log: true