- name: "Check current CC mode for GPU {{ gpu_bdf }}"
  ansible.builtin.command:
    cmd: "python3 ./nvidia_gpu_tools.py --gpu-bdf={{ gpu_bdf }} --get-cc-mode"
    chdir: "{{ shared_dir }}/nvtrust/host_tools/python/gpu-admin-tools"
  become: yes
  register: current_gpu_mode
  changed_when: false
  failed_when: false

- name: "Set CC mode to devtools for GPU {{ gpu_bdf }} if not already set"
  ansible.builtin.command:
    cmd: "python3 ./nvidia_gpu_tools.py --gpu-bdf={{ gpu_bdf }} --set-cc-mode=devtools --reset-after-cc-mode-switch"
    chdir: "{{ shared_dir }}/nvtrust/host_tools/python/gpu-admin-tools"
  become: yes
  when: "'devtools' not in current_gpu_mode.stdout | default('')"
