---
k3s_version: v1.33.1+k3s1
k3s_server_location: /var/lib/rancher/k3s
systemd_dir: /etc/systemd/system # noqa var-naming[no-role-prefix]
k3s_api_port: 6443
user_kubectl: true # noqa var-naming[no-role-prefix]
k3s_extra_server_args: ""
api_endpoint: "{{ hostvars[groups['control'][0]]['wireguard_ip'] }}"
k3s_server_config_yaml: |-
  write-kubeconfig-mode: "0644"
  disable:
    - traefik
    - servicelb
  node-ip: {{ wireguard_ip }}
  node-external-ip: {{ wireguard_ip }}
  advertise-address: {{ wireguard_ip }}
  flannel-iface: wg0
  flannel-external-ip: true

extra_agent_args: "--flannel-iface wg0"