---
- name: Install k3s
  ansible.builtin.include_tasks: install.yml
  tags: k3s-install

- name: Setup node
  ansible.builtin.include_tasks: setup_node.yml
  tags: k3s-node

- name: Setup k3s kubectl
  ansible.builtin.include_tasks: setup_kubectl.yml
  tags: k3s-kubectl

- name: Setup namespaces
  ansible.builtin.include_tasks: setup_namespaces.yml
  tags: namespaces

- name: Add chutes labels to nodes
  kubernetes.core.k8s:
    state: present
    kind: Node
    name: "{{ inventory_hostname }}"
    context: "{{ inventory_hostname }}"
    definition:
      metadata:
        labels:
          chutes/external-ip: "{{ ansible_host }}"
    merge_type: strategic-merge
  when: inventory_hostname in groups['workers']
