---
- name: Ensure chutes namespace exists
  when: inventory_hostname in groups['control']
  block:
    - name: Ensure namespace exists for control plane
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "chutes"
        context: "{{ inventory_hostname }}"
        state: present

    - name: Ensure namespace exists for API context
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "chutes"
        context: "karmada-apiserver"
        state: present