{{ if .Values.multiCluster }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agent-pdb
  namespace: chutes
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: agent
{{- end }}