---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chutes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chutes
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete", "create", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chutes
subjects:
- kind: ServiceAccount
  name: chutes
  namespace: chutes
roleRef:
  kind: Role
  name: chutes
  apiGroup: rbac.authorization.k8s.io