apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chutes-network-policy
spec:
  podSelector:
    matchLabels:
      chutes/chute: "true"
    matchExpressions:
      - key: chutes/job
        operator: NotIn
        values:
          - "true"
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 8001
  egress:
    # DNS resolution
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # External HTTPS traffic (excluding private networks)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              - 169.254.0.0/16
              - 100.64.0.0/10
      ports:
        - protocol: TCP
          port: 443

    # Squid proxy access
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: chutes-squid
      ports:
        - protocol: TCP
          port: 3128

    # Kubernetes API server access (default namespace, any TCP port)
    - to:
        - namespaceSelector:
            matchLabels:
              name: default
      ports:
        - protocol: TCP
