{{ if .Values.multiCluster }}
---
apiVersion: v1
kind: Secret
metadata:
  name: miner-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- $minerCredentials := lookup "v1" "Secret" .Release.Namespace "miner-credentials" }}
  {{- if $minerCredentials }}
  {{- range $key := list "ss58" "seed" "privateKey" }}
  {{- if hasKey $minerCredentials.data $key }}
  {{ $key }}: {{ index $minerCredentials.data $key }}
  {{- end }}
  {{- end }}
  {{- else }}
  {{- if not (or .Values.minerCredentials.secretSeed .Values.minerCredentials.privateKey) }}
  {{- fail "minerCredentials.secretSeed or minerCredentials.privateKey is required" }}
  {{- end }}
  ss58: {{ .Values.minerCredentials.ss58Address | b64enc | quote }}
  {{- with .Values.minerCredentials.secretSeed }}
  seed: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.minerCredentials.privateKey }}
  privateKey: {{ . | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}