{{ if .Values.multiCluster }}
---
apiVersion: v1
kind: Secret
metadata:
  name: miner-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- $minerCredentials := lookup "v1" "Secret" .Release.Namespace "miner-credentials" }}
  ss58: {{ if $minerCredentials }}{{ index $minerCredentials.data "ss58" }}{{ else }}{{ .Values.minerCredentials.ss58Address | b64enc | quote }}{{ end }}
  seed: {{ if $minerCredentials }}{{ index $minerCredentials.data "seed" }}{{ else }}{{ .Values.minerCredentials.secretSeed | b64enc | quote }}{{ end }}
{{- end }}