apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "registry.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "registry.labels" . | nindent 8 }}
    spec:
      {{- with .Values.registry.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: registry
          image: "{{ .Values.registry.image }}"
          imagePullPolicy: {{ .Values.registry.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.registry.resources | nindent 12 }}
          volumeMounts:
            - name: registry-nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: auth
          image: "{{ .Values.auth.image }}"
          imagePullPolicy: {{ .Values.auth.imagePullPolicy }}
          env:
            - name: MINER_SS58
              valueFrom:
                secretKeyRef:
                  name: miner-credentials
                  key: ss58
            - name: MINER_SEED
              valueFrom:
                secretKeyRef:
                  name: miner-credentials
                  key: seed
            - name: VALIDATORS
              value: {{ .Values.validators | toJson | quote }}
          ports:
            - name: auth
              containerPort: {{ .Values.auth.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.auth.resources | nindent 12 }}
      volumes:
        - name: registry-nginx-config
          configMap:
            name: registry-nginx-config
