---
# Common variables for all hosts

# System configuration
ansible_port: 22
ansible_ssh_common_args: -o StrictHostKeyChecking=no
timezone: UTC
swap_disable: true

# System packages to install
system_packages:
  - curl
  - wget
  - vim
  - net-tools
  - socat
  - conntrack
  - ipset
  - jq
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common

# Networking configuration (used by all)
k3s_api_port: "6443"
cluster_cidr: 10.42.0.0/16
service_cidr: 10.43.0.0/16

# K3s Configuration
k3s_version: v1.33.1+k3s1

# Ubuntu major/minor version.
ubuntu_major: "22"
ubuntu_minor: "04"
# CUDA version - leave as-is unless using h200s, in which case either use 12-5 or skip_cuda: true (if provider already pre-installed drivers)
cuda_version: "12-9"
# NVIDA GPU drivers - leave as-is unless using h200s, in which case it would be 555
nvidia_version: "575"
# Flag to skip the cuda install entirely, if the provider already has cuda 12.x+ installed (note some chutes will not work unless 12.6+)
skip_cuda: false
# Flag to enable/disable IPv6. Some hosts may require IPv6 to be on.
ipv6_enabled: true

# Chutes config
validator: 5Dt7HZ7Zpw4DppPxFM7Ke3Cm7sDAWhsZXmM5ZAmE7dSVJbcQ
