{{- if .Values.prometheus.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/component: server
  ingress:
  {{- range .Values.prometheus.networkPolicy.allowedCIDRs }}
  - from:
    - ipBlock:
        cidr: {{ . }}
    ports:
    - protocol: TCP
      port: 9090
  {{- end }}
{{- end }}