class DuplicateServer(Exception): ...


class NonEmptyServer(Exception): ...


class GPUlessServer(Exception): ...


class DeploymentFailure(Exception): ...

class BootstrapFailure(Exception): ...

class GraValBootstrapFailure(BootstrapFailure): ...
