---
# inventory.yml
all:
  children:
    control:
      hosts:
        chutes-miner-cpu-0:
          ansible_host: 52.90.127.45
    workers:
      hosts:
        chutes-miner-gpu-0:
          ansible_host: 64.247.206.27
          ansible_user: shadeform
          ansible_ssh_private_key_file: ~/.ssh/shadeform.pem

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/ec2.pem
    ssh_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQzuY35vbmwR97Ew3i6rnh4s1tGnNY8rg0V1Catis1gvfu+fSf5kZwCkb28AM39JeroUyVVekFq6MsSykvb2B8yz3OlUFaOer9NMm+62/5Rrd6ATNaZtBUtJ/Kf070YUWEAL9DNYQLNUF9zO5/BKFDrrWBJE8FoBltKKQ+4uw1itZ40+qrAm1uFsU8F20YN5o3GTfGwOud6ObHNEKpRy0MBrrqK1BBQVrWryBl+YLprtjSZ5TuiwVvZeYithX8jwlOlZy0uYueS8FesrbFMOZr05A08+9zRuKq0QVzLg+XF+IU804ntFjG+yCERczvK1geadKOrMxjTjg8wvtrSUx0ACimo4GkYGK9DGHop1pgVnylUe5F7fUiAlnhHLLHAPJBl44DX//e9FUeb6AkzbvzUPMnoXRQbgQThbetYg5wlImsPr9lmfKN2Ufg25EHFInTK0FNZzdp7f/KbJRJuDR6cfO6irBYbQEv+sC+yJG+2UQDIrIKdj+vMvE+erKVjVa80/eu7h8qyiCV+YXO+bgdpnV1DHCGCAvndaMnbvgnUwYIgMpRa8EQfcpY1VIhJmoo3RcjA1qzJFNLvwf2U8ht/ClafbeNn/SunFegqoSgHjt7CKTPJN8hv4feBjrD+jVC8v7Rs3UH7jsUUHnGBM4rY6nv5l33++RYXAO9AEXOiQ== kyle@chutes.ai"
    # The username you want to use to login to those machines (and your public key will be added to).
    user: kyle

    # Local kubectl setup
    setup_local_kubeconfig: true
    controller_kubeconfig: ~/.kube/chutes.config
    controller_kubectl_staging_dir: "{{ '~/.kube' | expanduser }}/chutes-staging" # noqa var-naming[no-role-prefix]