---
- name: Add NVIDIA Helm repository
  kubernetes.core.helm_repository:
    name: nvidia
    repo_url: https://helm.ngc.nvidia.com/nvidia

- name: Install GPU Operator
  kubernetes.core.helm:
    name: gpu-operator
    chart_ref: nvidia/gpu-operator
    release_namespace: gpu-operator
    create_namespace: true
    state: present
    force: true
    values:
      driver:
        enabled: false
      toolkit:
        enabled: false
      operator:
        upgradeCRD: false
