---
- name: Monitoring setup
  tags: monitoring
  block:
    - name: Add Prometheus Community Helm repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Add Metrics Server Helm repository
      kubernetes.core.helm_repository:
        name: metrics-server
        repo_url: https://kubernetes-sigs.github.io/metrics-server/

    - name: Add Kubernetes Dashboard Helm repository
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard/

    - name: Update Helm repositories
      shell: helm repo update

    - name: Install Prometheus
      shell: |
        helm upgrade --install prometheus prometheus-community/prometheus \
          --namespace monitoring \
          --create-namespace \
          --set server.persistentVolume.enabled=false \
          --set alertmanager.persistentVolume.enabled=false \
          --set prometheus-pushgateway.persistentVolume.enabled=false \
          --set prometheus-server.persistentVolume.enabled=false \
          --set alertmanager.persistence.enabled=false \
          --kubeconfig=/etc/rancher/k3s/k3s.yaml

    - name: Install kubernetes dashboard
      shell: |
        helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard \
          --create-namespace \
          --namespace kubernetes-dashboard \
          --set persistence.enabled=false \
          --kubeconfig=/etc/rancher/k3s/k3s.yaml
